#!/bin/bash
#@Author Shahriar Shovon
#@Github https://github.com/shovon8/sysmon
printf "%-10s%-15s%-15s%s\n" "PID" "ID" "MEMORY" "COMMAND"

function sysmon_main() {
    RAWIN=$(ps -o pid,user,%mem,command ax | grep ceph-osd | grep -v "podman" | grep -v "grep" | grep -v PID | awk '/[0-9]*/{print $1 ":" $2 ":" $4 ":" substr($0, index($0, "osd."),6)}')

    #id_opt = "-n"
    for i in $RAWIN
    do
#echo "----"
#echo $i
        PID=$(echo $i | cut -d: -f1)
        #OWNER=$(echo $i | cut -d: -f2)
        COMMAND=$(echo $i | cut -d: -f3)
        ID=$(echo $i | cut -d: -f4)
        #MEMORY=$(pmap $PID | tail -n 1)
        MEMORY=$(pmap $PID | tail -n 1 | awk '/[0-9]/{print $4/1024/1024}')
        
        printf "%-10s%-15s%-15s%s\n" "$PID" "$ID" "$MEMORY" "$COMMAND"
    done
}

sysmon_main | sort -bnr -k3
